const PAIRS: [string, string][] = [
  ['а', 'a'],
  ['А', 'a'],
  ['е', 'e'],
  ['Е', 'e'],
  ['о', 'o'],
  ['О', 'o'],
  ['р', 'p'],
  ['Р', 'p'],
  ['с', 'c'],
  ['С', 'c'],
  ['у', 'y'],
  ['У', 'y'],
  ['х', 'x'],
  ['Х', 'x'],
  ['і', 'i'],
  ['І', 'i'],
  ['ї', 'i'],
  ['Ї', 'i'],
  ['ј', 'j'],
  ['Ј', 'j'],
  ['ѕ', 's'],
  ['Ѕ', 's'],
  ['һ', 'h'],
  ['Һ', 'h'],
  ['ԁ', 'd'],
  ['Ԍ', 'g'],
  ['ԛ', 'q'],
  ['ԝ', 'w'],
  ['Υ', 'y'],
  ['α', 'a'],
  ['Α', 'a'],
  ['ε', 'e'],
  ['Ε', 'e'],
  ['ι', 'i'],
  ['Ι', 'i'],
  ['ο', 'o'],
  ['Ο', 'o'],
  ['ν', 'v'],
  ['Ν', 'n'],
  ['ρ', 'p'],
  ['Ρ', 'p'],
  ['τ', 't'],
  ['Τ', 't'],
  ['χ', 'x'],
  ['Χ', 'x'],
  ['η', 'n'],
  ['Η', 'h'],
  ['κ', 'k'],
  ['Κ', 'k'],
  ['μ', 'm'],
  ['Μ', 'm'],
  ['β', 'b'],
  ['Β', 'b'],
  ['ɡ', 'g'],
  ['ɢ', 'g'],
  ['ɪ', 'i'],
  ['ʏ', 'y'],
  ['ø', 'o'],
  ['Ø', 'o'],
  ['þ', 'p'],
  ['Þ', 'p'],
  ['ð', 'd'],
  ['Ð', 'd'],
  ['ł', 'l'],
  ['Ł', 'l'],
  ['ß', 'ss'],
  ['ſ', 's'],
  ['K', 'k'],
  ['Ⅰ', 'i'],
  ['ⅰ', 'i'],
  ['０', '0'],
  ['１', '1'],
  ['２', '2'],
  ['３', '3'],
  ['４', '4'],
  ['５', '5'],
  ['６', '6'],
  ['７', '7'],
  ['８', '8'],
  ['９', '9'],
];

for (let code = 0xff21; code <= 0xff3a; code++) {
  PAIRS.push([String.fromCharCode(code), String.fromCharCode(code - 0xff21 + 65)]);
}
for (let code = 0xff41; code <= 0xff5a; code++) {
  PAIRS.push([String.fromCharCode(code), String.fromCharCode(code - 0xff41 + 97)]);
}

const CONFUSABLES = new Map(PAIRS);

export function mapConfusables(value: string): string {
  let mapped = '';
  for (const char of value) mapped += CONFUSABLES.get(char) ?? char;
  return mapped;
}
