-- Migration: JagSMP Minecraft Account Linking
-- Description: Tables for linking Minecraft accounts to QTI accounts
-- Date: 2026-01-10

-- Table: minecraft_accounts
-- Stores linked Minecraft accounts with player UUIDs and usernames
CREATE TABLE IF NOT EXISTS minecraft_accounts (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    user_id TEXT NOT NULL,
    minecraft_uuid TEXT NOT NULL UNIQUE,
    minecraft_username TEXT NOT NULL,
    linked_at INTEGER NOT NULL DEFAULT (unixepoch()),
    last_updated INTEGER NOT NULL DEFAULT (unixepoch()),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_minecraft_accounts_user_id ON minecraft_accounts(user_id);
CREATE INDEX idx_minecraft_accounts_minecraft_uuid ON minecraft_accounts(minecraft_uuid);

-- Table: minecraft_link_codes
-- Temporary codes generated by /qtilink command for account verification
CREATE TABLE IF NOT EXISTS minecraft_link_codes (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    code TEXT NOT NULL UNIQUE,
    minecraft_uuid TEXT NOT NULL,
    minecraft_username TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch()),
    expires_at INTEGER NOT NULL,
    used INTEGER DEFAULT 0,
    used_by_user_id TEXT,
    used_at INTEGER,
    FOREIGN KEY (used_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_minecraft_link_codes_code ON minecraft_link_codes(code);
CREATE INDEX idx_minecraft_link_codes_expires ON minecraft_link_codes(expires_at);
CREATE INDEX idx_minecraft_link_codes_minecraft_uuid ON minecraft_link_codes(minecraft_uuid);

-- Table: minecraft_unlink_cooldowns
-- Tracks unlinking cooldowns to prevent abuse (7-day cooldown)
CREATE TABLE IF NOT EXISTS minecraft_unlink_cooldowns (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    user_id TEXT NOT NULL,
    unlinked_at INTEGER NOT NULL DEFAULT (unixepoch()),
    can_link_again_at INTEGER NOT NULL,
    previous_minecraft_uuid TEXT,
    previous_minecraft_username TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_minecraft_unlink_cooldowns_user_id ON minecraft_unlink_cooldowns(user_id);
CREATE INDEX idx_minecraft_unlink_cooldowns_can_link_again ON minecraft_unlink_cooldowns(can_link_again_at);

-- Table: minecraft_player_stats
-- Stores player statistics from the Minecraft server
CREATE TABLE IF NOT EXISTS minecraft_player_stats (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    minecraft_uuid TEXT NOT NULL UNIQUE,

    -- Playtime & Activity Stats
    total_playtime_minutes INTEGER DEFAULT 0,
    first_joined INTEGER,
    last_seen INTEGER,
    total_sessions INTEGER DEFAULT 0,

    -- PvP & Combat Stats
    player_kills INTEGER DEFAULT 0,
    deaths INTEGER DEFAULT 0,
    mob_kills INTEGER DEFAULT 0,
    damage_dealt REAL DEFAULT 0.0,
    damage_taken REAL DEFAULT 0.0,

    -- Additional stats as JSON for flexibility
    stats_json TEXT DEFAULT '{}',

    -- Metadata
    last_updated INTEGER NOT NULL DEFAULT (unixepoch()),

    FOREIGN KEY (minecraft_uuid) REFERENCES minecraft_accounts(minecraft_uuid) ON DELETE CASCADE
);

CREATE INDEX idx_minecraft_player_stats_minecraft_uuid ON minecraft_player_stats(minecraft_uuid);
CREATE INDEX idx_minecraft_player_stats_last_updated ON minecraft_player_stats(last_updated);

-- Table: minecraft_achievements
-- Server-specific achievements for JagSMP
CREATE TABLE IF NOT EXISTS minecraft_achievements (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    achievement_key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    icon_url TEXT,
    points INTEGER DEFAULT 0,
    category TEXT DEFAULT 'general',
    is_secret INTEGER DEFAULT 0,
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE INDEX idx_minecraft_achievements_category ON minecraft_achievements(category);

-- Table: minecraft_player_achievements
-- Tracks which achievements players have unlocked
CREATE TABLE IF NOT EXISTS minecraft_player_achievements (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    minecraft_uuid TEXT NOT NULL,
    achievement_id TEXT NOT NULL,
    unlocked_at INTEGER NOT NULL DEFAULT (unixepoch()),
    FOREIGN KEY (minecraft_uuid) REFERENCES minecraft_accounts(minecraft_uuid) ON DELETE CASCADE,
    FOREIGN KEY (achievement_id) REFERENCES minecraft_achievements(id) ON DELETE CASCADE,
    UNIQUE(minecraft_uuid, achievement_id)
);

CREATE INDEX idx_minecraft_player_achievements_minecraft_uuid ON minecraft_player_achievements(minecraft_uuid);
CREATE INDEX idx_minecraft_player_achievements_achievement_id ON minecraft_player_achievements(achievement_id);

-- Table: minecraft_activity_log
-- Recent activity feed for players
CREATE TABLE IF NOT EXISTS minecraft_activity_log (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    minecraft_uuid TEXT NOT NULL,
    activity_type TEXT NOT NULL, -- 'login', 'logout', 'achievement', 'death', 'kill', etc.
    activity_data TEXT DEFAULT '{}', -- JSON with additional context
    occurred_at INTEGER NOT NULL DEFAULT (unixepoch()),
    FOREIGN KEY (minecraft_uuid) REFERENCES minecraft_accounts(minecraft_uuid) ON DELETE CASCADE
);

CREATE INDEX idx_minecraft_activity_log_minecraft_uuid ON minecraft_activity_log(minecraft_uuid);
CREATE INDEX idx_minecraft_activity_log_occurred_at ON minecraft_activity_log(occurred_at);

-- Insert some default achievements
INSERT INTO minecraft_achievements (achievement_key, name, description, category, points) VALUES
('first_join', 'Welcome to JagSMP!', 'Join the server for the first time', 'milestone', 10),
('playtime_1h', 'Getting Started', 'Play for 1 hour', 'playtime', 15),
('playtime_10h', 'Regular Player', 'Play for 10 hours', 'playtime', 25),
('playtime_50h', 'Dedicated Member', 'Play for 50 hours', 'playtime', 50),
('playtime_100h', 'Server Veteran', 'Play for 100 hours', 'playtime', 100),
('first_kill', 'First Blood', 'Get your first player kill', 'pvp', 15),
('kill_streak_5', 'On Fire!', 'Get 5 kills without dying', 'pvp', 30),
('deaths_0', 'Untouchable', 'Play for 5 hours without dying', 'pvp', 50),
('kdr_2', 'Warrior', 'Achieve a 2.0 K/D ratio with at least 50 kills', 'pvp', 40);
