import { defineErrors } from '@qtiauth/service-kit';

export const GAMES_ERRORS = defineErrors({
  GAMES_NOT_FOUND: { status: 404, title: 'No such game' },
  GAMES_SLUG_TAKEN: { status: 409, title: 'That slug is already in use' },
  GAMES_INVALID: { status: 400, title: 'This game or product is not valid' },
  GAMES_PRODUCT_NOT_FOUND: { status: 404, title: 'No such product' },
  GAMES_PRODUCT_BASE: { status: 409, title: 'The base product stays with the game' },
  GAMES_PRODUCT_IN_USE: { status: 409, title: 'This product still has entitlements' },
  GAMES_USER_NOT_FOUND: { status: 404, title: 'No such user' },
  GAMES_ENTITLEMENT_NOT_FOUND: { status: 404, title: 'No such entitlement' },
  GAMES_ENTITLEMENT_REVOKED: { status: 409, title: 'This entitlement is already revoked' },
  GAMES_ENTITLEMENT_EXPIRED: { status: 400, title: 'The expiry is already in the past' },
  GAMES_CLIENT_NOT_ALLOWED: { status: 403, title: 'This client cannot act for that game' },
  GAMES_SERVER_UNAVAILABLE: { status: 503, title: 'The game server credential could not be saved' },
  GAMES_IDENTITY_UNAVAILABLE: { status: 503, title: 'The account service could not be reached' },
  GAMES_KEYS_DISABLED: { status: 409, title: 'Key redemption is disabled' },
  GAMES_KEY_INVALID: { status: 404, title: 'That key was not recognised' },
  GAMES_KEY_ALREADY_REDEEMED: { status: 409, title: 'That key has already been redeemed' },
  GAMES_KEY_REVOKED: { status: 409, title: 'That key has been revoked' },
  GAMES_KEY_EXPIRED: { status: 409, title: 'That key has expired' },
  GAMES_KEY_ALREADY_OWNED: { status: 409, title: 'You already own this product' },
  GAMES_KEY_BATCH_NOT_FOUND: { status: 404, title: 'No such key batch' },
  GAMES_KEY_BATCH_REVOKED: { status: 409, title: 'This key batch is already revoked' },
  GAMES_KEY_BATCH_INVALID: { status: 400, title: 'This key batch is not valid' },
  GAMES_CAPTCHA_REQUIRED: { status: 403, title: 'Complete the CAPTCHA to continue' },
  GAMES_CAPTCHA_INVALID: { status: 400, title: 'The CAPTCHA was not accepted' },
  GAMES_ACHIEVEMENT_NOT_FOUND: { status: 404, title: 'No such achievement' },
  GAMES_ACHIEVEMENT_SLUG_TAKEN: { status: 409, title: 'That achievement slug is already in use' },
  GAMES_ACHIEVEMENT_INVALID: { status: 400, title: 'This achievement is not valid' },
  GAMES_ACHIEVEMENT_NOT_PROGRESS: {
    status: 409,
    title: 'This achievement is not a progress achievement',
  },
  GAMES_ACHIEVEMENT_WRONG_GAME: {
    status: 403,
    title: 'This token cannot act on that game',
  },
  GAMES_ACHIEVEMENT_UNLOCK_NOT_FOUND: { status: 404, title: 'No such achievement unlock' },
  GAMES_ACHIEVEMENT_UNLOCK_NOT_UNLOCKED: {
    status: 409,
    title: 'This achievement is not currently unlocked',
  },
  GAMES_STAT_NOT_FOUND: { status: 404, title: 'No such stat' },
  GAMES_STAT_KEY_TAKEN: { status: 409, title: 'That stat key is already in use' },
  GAMES_STAT_INVALID: { status: 400, title: 'This stat is not valid' },
  GAMES_STAT_AUTHORITY_MISMATCH: {
    status: 403,
    title: 'This stat needs a game-authoritative write',
  },
  GAMES_STAT_DELTA_TOO_LARGE: { status: 400, title: 'The change exceeds the stat max delta' },
  GAMES_LEADERBOARD_NOT_FOUND: { status: 404, title: 'No such leaderboard' },
  GAMES_LEADERBOARD_SLUG_TAKEN: { status: 409, title: 'That leaderboard slug is already in use' },
  GAMES_LEADERBOARD_REQUIRES_GAME_AUTHORITY: {
    status: 409,
    title: 'This leaderboard needs a stat with authority: game',
  },
  GAMES_LEADERBOARD_ENTRY_NOT_FOUND: { status: 404, title: 'No such leaderboard entry' },
  GAMES_PLAYTIME_DISABLED: { status: 409, title: 'Playtime tracking is disabled' },
  GAMES_PLAYTIME_SESSION_NOT_FOUND: { status: 404, title: 'No such playtime session' },
  GAMES_PLAYTIME_LIMIT_REACHED: {
    status: 409,
    title: 'The daily playtime limit for this account has been reached',
  },
  GAMES_CUSTOM_DATA_TOO_LARGE: { status: 413, title: 'Custom data exceeds the size limit' },
  GAMES_LICENSING_DISABLED: { status: 409, title: 'Offline licensing is disabled' },
  GAMES_LICENSING_NOT_OWNED: {
    status: 403,
    title: 'Only owners of this game can issue a licence lease',
  },
  GAMES_LICENSING_DEVICE_REQUIRED: {
    status: 400,
    title: 'This game requires a device_id when issuing a lease',
  },
  GAMES_LICENSING_DEVICE_LIMIT: {
    status: 409,
    title: 'You have reached the device limit for this game',
  },
  GAMES_LICENSING_LEASE_NOT_FOUND: { status: 404, title: 'No such licence lease' },
  GAMES_LICENSING_LEASE_REVOKED: { status: 409, title: 'This licence lease is already revoked' },
  GAMES_LICENSING_INVALID: { status: 400, title: 'The lease token is not valid' },
  GAMES_LICENSING_KEY_UNAVAILABLE: {
    status: 503,
    title: 'The licensing signing key is not loaded',
  },
  GAMES_CLOUD_SAVES_DISABLED: { status: 409, title: 'Cloud saves are disabled' },
  GAMES_CLOUD_SAVES_UNAVAILABLE: {
    status: 503,
    title: 'Cloud save storage is not available',
  },
  GAMES_CLOUD_SAVE_SLOT_LIMIT: {
    status: 409,
    title: 'You have reached the cloud save slot limit for this game',
  },
  GAMES_CLOUD_SAVE_QUOTA: { status: 413, title: 'Cloud save quota exceeded' },
  GAMES_CLOUD_SAVE_TOO_LARGE: {
    status: 413,
    title: 'Cloud save version exceeds the size limit',
  },
  GAMES_CLOUD_SAVE_CONFLICT: {
    status: 409,
    title: 'The base_version does not match the current version',
  },
  GAMES_CLOUD_SAVE_NOT_FOUND: { status: 404, title: 'No such cloud save' },
  GAMES_CLOUD_SAVE_VERSION_NOT_FOUND: {
    status: 404,
    title: 'No such cloud save version',
  },
  GAMES_CLOUD_SAVE_NOT_COMMITTED: {
    status: 409,
    title: 'This cloud save version has not been committed',
  },
  GAMES_CLOUD_SAVE_ALREADY_COMMITTED: {
    status: 409,
    title: 'This cloud save version is already committed',
  },
});
