import { defineErrors } from '@qtiauth/service-kit';

export const GAMES_ERRORS = defineErrors({
  GAMES_NOT_FOUND: { status: 404, title: 'No such game' },
  GAMES_SLUG_TAKEN: { status: 409, title: 'That slug is already in use' },
  GAMES_INVALID: { status: 400, title: 'This game or product is not valid' },
  GAMES_PRODUCT_NOT_FOUND: { status: 404, title: 'No such product' },
  GAMES_PRODUCT_BASE: { status: 409, title: 'The base product stays with the game' },
  GAMES_PRODUCT_IN_USE: { status: 409, title: 'This product still has entitlements' },
  GAMES_USER_NOT_FOUND: { status: 404, title: 'No such user' },
  GAMES_ENTITLEMENT_NOT_FOUND: { status: 404, title: 'No such entitlement' },
  GAMES_ENTITLEMENT_REVOKED: { status: 409, title: 'This entitlement is already revoked' },
  GAMES_ENTITLEMENT_EXPIRED: { status: 400, title: 'The expiry is already in the past' },
  GAMES_CLIENT_NOT_ALLOWED: { status: 403, title: 'This client cannot act for that game' },
  GAMES_SERVER_UNAVAILABLE: { status: 503, title: 'The game server credential could not be saved' },
  GAMES_IDENTITY_UNAVAILABLE: { status: 503, title: 'The account service could not be reached' },
  GAMES_KEYS_DISABLED: { status: 409, title: 'Key redemption is disabled' },
  GAMES_KEY_INVALID: { status: 404, title: 'That key was not recognised' },
  GAMES_KEY_ALREADY_REDEEMED: { status: 409, title: 'That key has already been redeemed' },
  GAMES_KEY_REVOKED: { status: 409, title: 'That key has been revoked' },
  GAMES_KEY_EXPIRED: { status: 409, title: 'That key has expired' },
  GAMES_KEY_ALREADY_OWNED: { status: 409, title: 'You already own this product' },
  GAMES_KEY_BATCH_NOT_FOUND: { status: 404, title: 'No such key batch' },
  GAMES_KEY_BATCH_REVOKED: { status: 409, title: 'This key batch is already revoked' },
  GAMES_KEY_BATCH_INVALID: { status: 400, title: 'This key batch is not valid' },
  GAMES_CAPTCHA_REQUIRED: { status: 403, title: 'Complete the CAPTCHA to continue' },
  GAMES_CAPTCHA_INVALID: { status: 400, title: 'The CAPTCHA was not accepted' },
  GAMES_ACHIEVEMENT_NOT_FOUND: { status: 404, title: 'No such achievement' },
  GAMES_ACHIEVEMENT_SLUG_TAKEN: { status: 409, title: 'That achievement slug is already in use' },
  GAMES_ACHIEVEMENT_INVALID: { status: 400, title: 'This achievement is not valid' },
  GAMES_ACHIEVEMENT_NOT_PROGRESS: {
    status: 409,
    title: 'This achievement is not a progress achievement',
  },
  GAMES_ACHIEVEMENT_WRONG_GAME: {
    status: 403,
    title: 'This token cannot act on that game',
  },
  GAMES_ACHIEVEMENT_UNLOCK_NOT_FOUND: { status: 404, title: 'No such achievement unlock' },
  GAMES_ACHIEVEMENT_UNLOCK_NOT_UNLOCKED: {
    status: 409,
    title: 'This achievement is not currently unlocked',
  },
});
